title: Holiday
icon: benefits/np_holiday_200351_000000.png
color: '#FFB800'
updated_by: f5726654-dced-41d5-a2d4-80fc8ddc7ecb
updated_at: 1684937978
blueprint: category
order: 6
description: 'Time away from work is vital to your mental and physical health. Our leave entitlement helps support you to take time off to rest and relax.'
