title: 'Money & Finances'
color: '#006747'
order: 1
updated_by: f5726654-dced-41d5-a2d4-80fc8ddc7ecb
updated_at: 1685698482
blueprint: category
icon: benefits/noun-pound-4530758.png
description: 'We offer a range of financial benefits to colleagues beyond salary. From the NHS pension scheme, cost of living support, budgeting tools, urgent expert financial advice, through to support if you work remotely. There are a range of benefits on offer for you.'
