title: Recruitment
icon: benefits/np_recruitment_2428454_000000.png
color: '#980037'
updated_by: f5726654-dced-41d5-a2d4-80fc8ddc7ecb
updated_at: 1685443118
blueprint: category
order: 9
description: 'Thinking of joining our Trust, check out some additional benefits available to new members of staff.'
