title: 'Special Leave and Time Off Work'
description: |-
  Time off work when you are unwell, have a difficult situation or you need special leave to care for those you love.

  Our range of leave options is there to support you if you need to deal with a sensitive or upsetting situation. Alongside sick pay entitlements and enhanced special leave options to deal with a bereavement, pregnancy loss or to care for a loved one, we have added an additional paid day each year if you need to take time off to recover emotionally from any situation you are facing.
icon: logo-sl-1685691688.jpg
updated_by: f5726654-dced-41d5-a2d4-80fc8ddc7ecb
updated_at: 1685691708
blueprint: category
color: '#3F2A6F'
